language: python

python:
  - 3.6

services:
  - mysql

env:
  - DJANGO=2.1.4 DB=mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=attendance_system.settings

install:
  - pip3 install -r requirements.txt

before_script:
  - mysql -e "CREATE DATABASE attendance_system;"
  - mysql -e "CREATE USER 'xyz'@'localhost' IDENTIFIED BY 'pass@123';"
  - mysql -e "GRANT ALL PRIVILEGES ON attendance_system.* TO 'xyz'@'localhost';"
  - mysql -e "GRANT ALL PRIVILEGES ON test_attendance_system.* TO 'xyz'@'localhost';"
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - flake8
  - python3 manage.py test